#!/bin/bash

OUTPUT_FILE="/var/www/html/index.html"

if [ ! -d "/var/www/html" ]; then
    mkdir -p /var/www/html
fi

HOST=$(hostname)

NOW=$(date)

UPTIME=$(uptime -p)

RAM_USED=$(free -h | grep -i mem | awk '{print $3 "/" $2}')

DISK_USED=$(df -h | grep '/$' | awk '{print $5}')

cat <<EOF > "$OUTPUT_FILE"
<!DOCTYPE html>
<html>
<head>
    <title>Server Stats</title>
    <style>
        body { font-family: sans-serif; background-color: #222; color: #fff; text-align: center; padding: 50px; }
        .card { background-color: #333; padding: 20px; margin: 20px auto; width: 300px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.3); }
        h1 { color: #4CAF50; }
        .stat { font-size: 24px; font-weight: bold; color: #00bcd4; }
    </style>
</head>
<body>
    <h1> System Dashboard: $HOST</h1>
    <p>Last Updated: $NOW</p>

    <div class="card">
        <h3> Uptime</h3>
        <p class="stat">$UPTIME</p>
    </div>

    <div class="card">
        <h3> RAM Usage</h3>
        <p class="stat">$RAM_USED</p>
    </div>

    <div class="card">
        <h3> Disk Usage</h3>
        <p class="stat">$DISK_USED</p>
    </div>

    <p><em>Generated by Bash Script</em></p>
</body>
</html>
EOF
